2018-06-04 21:40:26,668 - log.py[line:22] - ERROR: https://api.zhihu.com/people/d2a34bd18214003d4e8628acbadb7315  HTTPSConnectionPool(host='api.zhihu.com', port=443): Max retries exceeded with url: /people/d2a34bd18214003d4e8628acbadb7315 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
2018-06-04 21:44:33,801 - log.py[line:22] - ERROR: https://api.zhihu.com/people/a03ef04e32dcce9867665d82e042a7af  HTTPSConnectionPool(host='api.zhihu.com', port=443): Max retries exceeded with url: /people/a03ef04e32dcce9867665d82e042a7af (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
2018-06-04 21:48:59,035 - log.py[line:22] - ERROR: https://api.zhihu.com/people/527c73af488c5766b430e5f9ea52372f  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
2018-06-04 21:59:51,854 - log.py[line:22] - ERROR: https://api.zhihu.com/people/813c640f25c3933ec7ec4b0b5b10f42e  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
2018-06-04 22:54:28,264 - log.py[line:22] - ERROR: https://api.zhihu.com/people/b8ea31d1b828857e7eb5bad7af7d30ce  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
